/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.sem6;

/**
 *
 * @author HP
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm2
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldVendedorDni = new javax.swing.JTextField();
        jTextFieldVendedorTasaComision = new javax.swing.JTextField();
        jTextFieldVendedorNombres = new javax.swing.JTextField();
        jTextFieldVendedorMontoVendido = new javax.swing.JTextField();
        jTextFieldVendedorApellidos = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVendedor = new javax.swing.JTextArea();
        jButtonVendedorCrear = new javax.swing.JButton();
        jButtonVendedorLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldPermanenteDni = new javax.swing.JTextField();
        jTextFieldPermanenteSueldoBase = new javax.swing.JTextField();
        jTextFieldPermanenteNombres = new javax.swing.JTextField();
        jTextFieldPermanenteApellidos = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaPermanente = new javax.swing.JTextArea();
        jButtonPermanenteCrear = new javax.swing.JButton();
        jButtonPermanenteLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxPermanenteTipoAfiliacion = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 41, 58));

        jPanel4.setBackground(new java.awt.Color(4, 28, 50));

        jTextFieldVendedorDni.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldVendedorDni.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldVendedorDni.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldVendedorDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldVendedorDni.setCaretColor(java.awt.Color.black);
        jTextFieldVendedorDni.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldVendedorDni.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldVendedorTasaComision.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldVendedorTasaComision.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldVendedorTasaComision.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldVendedorTasaComision.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldVendedorTasaComision.setCaretColor(java.awt.Color.black);
        jTextFieldVendedorTasaComision.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldVendedorTasaComision.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldVendedorNombres.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldVendedorNombres.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldVendedorNombres.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldVendedorNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldVendedorNombres.setCaretColor(java.awt.Color.black);
        jTextFieldVendedorNombres.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldVendedorNombres.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldVendedorMontoVendido.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldVendedorMontoVendido.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldVendedorMontoVendido.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldVendedorMontoVendido.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldVendedorMontoVendido.setCaretColor(java.awt.Color.black);
        jTextFieldVendedorMontoVendido.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldVendedorMontoVendido.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldVendedorApellidos.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldVendedorApellidos.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldVendedorApellidos.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldVendedorApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldVendedorApellidos.setCaretColor(java.awt.Color.black);
        jTextFieldVendedorApellidos.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldVendedorApellidos.setSelectionColor(new java.awt.Color(253, 84, 17));

        jScrollPane3.setBackground(new java.awt.Color(6, 70, 99));
        jScrollPane3.setBorder(null);

        jTextAreaVendedor.setBackground(new java.awt.Color(6, 70, 99));
        jTextAreaVendedor.setColumns(20);
        jTextAreaVendedor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextAreaVendedor.setForeground(java.awt.Color.white);
        jTextAreaVendedor.setRows(5);
        jTextAreaVendedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane3.setViewportView(jTextAreaVendedor);

        jButtonVendedorCrear.setBackground(java.awt.Color.red);
        jButtonVendedorCrear.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonVendedorCrear.setText("CREAR");
        jButtonVendedorCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonVendedorCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendedorCrearActionPerformed(evt);
            }
        });

        jButtonVendedorLimpiar.setBackground(java.awt.Color.cyan);
        jButtonVendedorLimpiar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonVendedorLimpiar.setForeground(java.awt.Color.darkGray);
        jButtonVendedorLimpiar.setText("LIMPIAR");
        jButtonVendedorLimpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonVendedorLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendedorLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("DNI");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("NOMBRES");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("APELLIDOS");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("MONTO VENDIDO");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("TASA COMISION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButtonVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButtonVendedorLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVendedorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVendedorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldVendedorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVendedorTasaComision, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldVendedorMontoVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVendedorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVendedorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVendedorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVendedorMontoVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVendedorTasaComision, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVendedorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVendedorLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Empleado vendedor", jPanel4);

        jPanel6.setBackground(new java.awt.Color(4, 28, 50));

        jTextFieldPermanenteDni.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldPermanenteDni.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldPermanenteDni.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldPermanenteDni.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldPermanenteDni.setCaretColor(java.awt.Color.black);
        jTextFieldPermanenteDni.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldPermanenteDni.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldPermanenteSueldoBase.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldPermanenteSueldoBase.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldPermanenteSueldoBase.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldPermanenteSueldoBase.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldPermanenteSueldoBase.setCaretColor(java.awt.Color.black);
        jTextFieldPermanenteSueldoBase.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldPermanenteSueldoBase.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldPermanenteNombres.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldPermanenteNombres.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldPermanenteNombres.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldPermanenteNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldPermanenteNombres.setCaretColor(java.awt.Color.black);
        jTextFieldPermanenteNombres.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldPermanenteNombres.setSelectionColor(new java.awt.Color(253, 84, 17));

        jTextFieldPermanenteApellidos.setBackground(new java.awt.Color(236, 179, 101));
        jTextFieldPermanenteApellidos.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldPermanenteApellidos.setForeground(new java.awt.Color(0, 7, 20));
        jTextFieldPermanenteApellidos.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
        jTextFieldPermanenteApellidos.setCaretColor(java.awt.Color.black);
        jTextFieldPermanenteApellidos.setSelectedTextColor(new java.awt.Color(0, 0, 117));
        jTextFieldPermanenteApellidos.setSelectionColor(new java.awt.Color(253, 84, 17));

        jScrollPane5.setBackground(new java.awt.Color(6, 70, 99));
        jScrollPane5.setBorder(null);

        jTextAreaPermanente.setBackground(new java.awt.Color(6, 70, 99));
        jTextAreaPermanente.setColumns(20);
        jTextAreaPermanente.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTextAreaPermanente.setForeground(java.awt.Color.white);
        jTextAreaPermanente.setRows(5);
        jTextAreaPermanente.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        jScrollPane5.setViewportView(jTextAreaPermanente);

        jButtonPermanenteCrear.setBackground(java.awt.Color.red);
        jButtonPermanenteCrear.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonPermanenteCrear.setText("CREAR");
        jButtonPermanenteCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPermanenteCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermanenteCrearActionPerformed(evt);
            }
        });

        jButtonPermanenteLimpiar.setBackground(java.awt.Color.cyan);
        jButtonPermanenteLimpiar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonPermanenteLimpiar.setForeground(java.awt.Color.darkGray);
        jButtonPermanenteLimpiar.setText("LIMPIAR");
        jButtonPermanenteLimpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonPermanenteLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermanenteLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("DNI");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("NOMBRES");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("APELLIDOS");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("TIPO AFILIACION");

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("SUELDO BASE");

        jComboBoxPermanenteTipoAfiliacion.setBackground(new java.awt.Color(236, 179, 101));
        jComboBoxPermanenteTipoAfiliacion.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jComboBoxPermanenteTipoAfiliacion.setForeground(new java.awt.Color(0, 7, 20));
        jComboBoxPermanenteTipoAfiliacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFP", "SNP" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jButtonPermanenteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButtonPermanenteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPermanenteDni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPermanenteNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPermanenteSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jComboBoxPermanenteTipoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldPermanenteApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPermanenteDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPermanenteNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPermanenteApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPermanenteSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPermanenteTipoAfiliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPermanenteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPermanenteLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Empleado permanente", jPanel6);

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("EMPLEADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVendedorCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendedorCrearActionPerformed
        // TODO add your handling code here:

            String vendedorDni = jTextFieldVendedorDni.getText();
            String vendedorNombres = jTextFieldVendedorNombres.getText();
            String vendedorApellidos = jTextFieldVendedorApellidos.getText();
            String vendedorMontoVendidoString = jTextFieldVendedorMontoVendido.getText();
            String vendedorTasaComisionString = jTextFieldVendedorTasaComision.getText();
            // TODO validar entradas
            double dVendedorMontoVendido = Double.parseDouble(vendedorMontoVendidoString);
            double dVendedorTasaComision = Double.parseDouble(vendedorTasaComisionString);
            EmpleadoVendedor empVendedor = new EmpleadoVendedor(vendedorDni, vendedorNombres, vendedorApellidos, dVendedorMontoVendido, dVendedorTasaComision);

            String vendedorInfo = empVendedor.getInfo();
            jTextAreaVendedor.setText(vendedorInfo);

    }//GEN-LAST:event_jButtonVendedorCrearActionPerformed

    private void jButtonPermanenteCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermanenteCrearActionPerformed
        // TODO add your handling code here:
        String permanenteDni = jTextFieldPermanenteDni.getText();
        String permanenteNombres = jTextFieldPermanenteNombres.getText();
        String permanenteApellidos = jTextFieldPermanenteApellidos.getText();
        String permanenteSueldoBaseString = jTextFieldPermanenteSueldoBase.getText();
        double permanenteSueldoBase = Double.parseDouble(permanenteSueldoBaseString);
        String permanenteTipoAfiliacion = jComboBoxPermanenteTipoAfiliacion.getSelectedItem().toString();
        // creamos el objeto
        //     public EmpleadoPermanente(String nDni, String nNombres, String nApellidos, double nSueldoBase, String nAfiliacion) {

        EmpleadoPermanente empPermanente = new EmpleadoPermanente(permanenteDni, permanenteNombres, permanenteApellidos, permanenteSueldoBase, permanenteTipoAfiliacion);
        String empPermanenteInformacion = empPermanente.getInfo();
        jTextAreaPermanente.setText(empPermanenteInformacion);
    }//GEN-LAST:event_jButtonPermanenteCrearActionPerformed

    private void jButtonVendedorLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendedorLimpiarActionPerformed
        // TODO add your handling code here:
        jTextAreaVendedor.setText("");
        jTextFieldVendedorDni.setText("");
        jTextFieldVendedorNombres.setText("");
        jTextFieldVendedorApellidos.setText("");
        jTextFieldVendedorMontoVendido.setText("");
        jTextFieldVendedorTasaComision.setText("");
        jTextFieldVendedorDni.requestFocus();
    }//GEN-LAST:event_jButtonVendedorLimpiarActionPerformed

    private void jButtonPermanenteLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermanenteLimpiarActionPerformed
        // TODO add your handling code here:
        jTextFieldPermanenteDni.setText("");
        jTextFieldPermanenteNombres.setText("");
        jTextFieldPermanenteApellidos.setText("");
        jTextFieldPermanenteSueldoBase.setText("");
        jTextAreaPermanente.setText("");
        // reseteamos el combo box
        jComboBoxPermanenteTipoAfiliacion.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonPermanenteLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPermanenteCrear;
    private javax.swing.JButton jButtonPermanenteLimpiar;
    private javax.swing.JButton jButtonVendedorCrear;
    private javax.swing.JButton jButtonVendedorLimpiar;
    private javax.swing.JComboBox<String> jComboBoxPermanenteTipoAfiliacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextAreaPermanente;
    private javax.swing.JTextArea jTextAreaVendedor;
    private javax.swing.JTextField jTextFieldPermanenteApellidos;
    private javax.swing.JTextField jTextFieldPermanenteDni;
    private javax.swing.JTextField jTextFieldPermanenteNombres;
    private javax.swing.JTextField jTextFieldPermanenteSueldoBase;
    private javax.swing.JTextField jTextFieldVendedorApellidos;
    private javax.swing.JTextField jTextFieldVendedorDni;
    private javax.swing.JTextField jTextFieldVendedorMontoVendido;
    private javax.swing.JTextField jTextFieldVendedorNombres;
    private javax.swing.JTextField jTextFieldVendedorTasaComision;
    // End of variables declaration//GEN-END:variables
}
